// Copyright (c) 2026 Glavo
// SPDX-License-Identifier: Apache-2.0

package org.glavo.m3fx.hmcl.demo;

import javafx.geometry.Rectangle2D;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import org.jetbrains.annotations.NotNullByDefault;
import org.jetbrains.annotations.Nullable;

import java.net.URL;
import java.util.Objects;

/// Resolves HMCL 3.16.2 images generated by the demo build.
///
/// Binary HMCL assets are not stored in this repository. The `hmcl-md3-demo` Gradle project downloads the tagged
/// source archive and maps selected images below this class's resource namespace before Java resources are
/// processed.
@NotNullByDefault
final class HMCLDemoAssets {
    /// The generated class-path prefix for HMCL images.
    private static final String RESOURCE_PREFIX = "/org/glavo/m3fx/hmcl/demo/assets/";

    /// Prevents utility-class instantiation.
    private HMCLDemoAssets() {
    }

    /// Returns the generated resource URL.
    ///
    /// @param relativePath the path relative to the generated HMCL asset namespace
    /// @return the resource URL
    /// @throws IllegalArgumentException if the resource is absent
    static URL resource(String relativePath) {
        String normalized = normalize(relativePath);
        @Nullable URL resource = HMCLDemoAssets.class.getResource(RESOURCE_PREFIX + normalized);
        if (resource == null) {
            throw new IllegalArgumentException("Missing generated HMCL asset: " + normalized);
        }
        return resource;
    }

    /// Loads a generated image.
    ///
    /// @param relativePath the generated image path
    /// @return the loaded image
    static Image image(String relativePath) {
        return new Image(resource(relativePath).toExternalForm(), true);
    }

    /// Creates an image view with bounded, aspect-preserving dimensions.
    ///
    /// @param relativePath the generated image path
    /// @param width        the requested fit width
    /// @param height       the requested fit height
    /// @return the configured image view
    static ImageView imageView(String relativePath, double width, double height) {
        ImageView view = new ImageView(image(relativePath));
        view.setFitWidth(width);
        view.setFitHeight(height);
        view.setPreserveRatio(true);
        view.setSmooth(true);
        return view;
    }

    /// Creates a square avatar view from the face area of a standard 64-by-64 Minecraft skin.
    ///
    /// @param relativePath the generated skin path
    /// @param size         the requested logical output size
    /// @return the configured face image view
    static ImageView skinFace(String relativePath, double size) {
        ImageView view = new ImageView(image(relativePath));
        view.setViewport(new Rectangle2D(8.0, 8.0, 8.0, 8.0));
        view.setFitWidth(size);
        view.setFitHeight(size);
        view.setPreserveRatio(false);
        view.setSmooth(false);
        return view;
    }

    /// Normalizes and validates a relative resource path.
    ///
    /// @param relativePath the caller-supplied relative path
    /// @return the normalized path
    private static String normalize(String relativePath) {
        String normalized = Objects.requireNonNull(relativePath, "relativePath").replace('\\', '/');
        while (normalized.startsWith("/")) {
            normalized = normalized.substring(1);
        }
        if (normalized.isBlank() || normalized.contains("../") || normalized.equals("..")) {
            throw new IllegalArgumentException("Invalid HMCL asset path: " + relativePath);
        }
        return normalized;
    }
}
